_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
llm_model:
    value: ollama/qwen3:8b
n_episodes:
    value: 5
use_wandb:
    value: true
